services:
  - type: web
    name: chat-app-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 8000
      - key: JWT_SECRET_KEY
        sync: false
      - key: MONGO_URI
        sync: false